### ISSUE TITLE
Using Symbols in actions that reach the reducer is not recommended

### ISSUE THREAD

**Issue by markerikson** [CodementorIO/redux-api-middleman#3]
The examples in the README suggest using Symbols for the success/failure action types.  Per http://redux.js.org/docs/FAQ.html#actions-string-constants , this is generally considered an anti-pattern.  It's fine to use Symbols for actions that will be intercepted by the middleware, but actions that reach the reducers should ideally be fully serializable.

**Comment by mz026** [comment]
@markerikson thanks a lot for pointing it out!!
I've updated the README, please let us know if there's any other issue.

Thanks!!

**Comment by markerikson** [comment]
Should be better.  Again, the code would have worked, just might not have run as expected if time-travel debugging and such.  :)
